config/routes.rb
Rails.application.routes.draw do
  #devise_for :user_admins

  devise_for :user_admins do
    get '/user_admins/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          resources :comments
        end
      end
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [ :index, :new, :create, :show, :destroy] 
    resources :comments, only: [ :create, :destroy]
    resources :likes, only: [ :create ]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post, public: true

    return unless user.present? # additional permissions for logged in users (they can read their own posts)

    can :read, Post, user: user

    return unless user.admin? # additional permissions for administrators

    can :read, Post
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :updates_likes_counter

  def updates_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  after_save :updates_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def updates_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  def all_comments
    comments.all
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_post
    posts.limit(3).order(created_at: :desc)
  end
end

app/models/user_admin.rb
class UserAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(_resource_or_scope)
    root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @user = Post.find(params[:user_id])
    @post = Post.find(params[:user_id])
    @comment = Comment.new(post_params)
    @comment.author = current_user_admin
    @comment.post = @post

    if @comment.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  def new
    @comment = Comment.new
  end

  def destroy
    post = Post.find(params[:post_id])
    Comment.destroy(params[:id])
    post.comments_counter -= 1
    post.save
    redirect_to user_posts_path(current_user_admin)
  end

  private

  def post_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/concerns/api/v1/application_controller.rb
module Api
  module V1
    class ApplicationController < ActionController::Base
      respond_to :json
    end
  end
end

app/controllers/concerns/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      before_action :authenticate_admin!

      def index
        comments = Comment.where(author_id: params[:post_id])
        render json: comments
      end

      def create
        @comment = Comment.new(text: params[:comment][:text], post_id:, user_id:)
        if @comment.save
          render json: @comment, status: :ok
        else
          render json: @comment.errors, status: :unprocessable_entity
        end
      end
    end
  end
end

app/controllers/concerns/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      before_action :authenticate_admin!
      def index
        @posts = Post.all
        @user = User.includes(posts: [:comments]).find(params[:user_id].to_i)
        render json: @posts
      end

      def show
        @post = Post.where(id: params[:id])
        render json: @post
      end
    end
  end
end

app/controllers/concerns/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      before_action :authenticate_admin!
      def index
        @users = User.all
        render json: @users
      end

      def show
        @user = User.find(params[:id])
        render json: @user
      end
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = Post.find(params[:user_id])
    @post = Post.find(params[:user_id])
    current_user_admin = User.find(params[:user_id])
    @like = current_user_admin.likes.new(
      author_id: current_user_admin.id,
      post_id: @post.id
    )
    if @like.save
      redirect_to user_posts_path(current_user_admin, @post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all
    @user = User.includes(posts: [:comments]).find(params[:user_id].to_i)
  end

  def current_ability
    @current_ability ||= Ability.new(current_user_admin)
  end

  def new
    @id = current_user_admin.id
    @post = Post.new
    @id = current_user_admin.id
  end

  def create
    post = Post.new(title: post_params[:title], text: post_params[:text], author: current_user_admin)
    @author = post.author

    if post.save
      redirect_to new_user_post_path(@author.id), message: 'Post was successfully created'
    else
      flash[:error] = 'Error:  Post was not created!!'
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    @title = @post.title
    @id.posts_counter -= 1

    respond_to do |format|
      format.html { redirect_to user_path(current_user_admin), notice: "Post #{@title} deleted!" }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_with model: Comment, url: user_comments_path(@user, @post), class: "commentform" do |comment_post|%>
    <div>
        <%= comment_post.text_field :text, placeholder: "Add new comment", class: "comment-btn"%>
    </div>
    
    <div>
        <%= comment_post.submit "Add comment", class: "comment-btn"%>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if  user_admin_signed_in? %>
  <p>Welcome <%= current_user_admin.full_name %>!</p>
  <%= link_to 'Sign out', user_admin_session_path, method: :delete %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<%= form_with model: Like, url: user_likes_path(@user, @post), class: "likeform" do |like_post|%>
    <div>
        <%= like_post.submit "Like Post", class: "like-btn"%>
    </div>
<%end%>

app/views/posts/_delete.html.erb
<% if can? :destroy, Post %>
<%= form_with model: @post, url: user_post_path(@user, @post), method: :delete do |f| %>
    <%= f.submit "Delete Post", class: "button" %>
<% end %>
<% end %>
 

app/views/posts/_form.html.erb
<%= form_with model: Post, url: user_posts_path, class: "form-create" do |pp| %>

    <% if @post.errors.any? %>
     <h2>The following errors prevented the article from saving:</h2>
     <ul>
     <% @post.errors.full_messages.each do |msg|%>
     <li><%= msg %></li>
     <% end %>
     </ul>
    <% end %>
    
    <p>
        <%= pp.label :title %>
        <%= pp.text_field :title %>
    </p>
    
    <p>
        <%= pp.label :text %>
        <%= pp.text_area :text  %>
    </p>
    
    <p>
        <%= pp.submit "submit", class: "submit-btn"%>
    </p>
    
    <%end%>
    

app/views/posts/index.html.erb
<p>post list</p>


 <%= link_to new_user_post_path(@user.id) do %>
        <div class="all_post">
            <button>create Post</button>
        </div>
    <%end%>

<div class="single_user_container">
    <div class="image_name_holder">
        <div class="user_image">
            <img src="<%= @user.photo %>" />
        </div>  

        <div class="name_container">
            <h1><%= @user.name %></h1> 
            <span>Number of posts: <%= @user.posts_counter%></span>
        </div>
     </div>

    <%@posts.each do |post|%>
        <%= link_to user_post_path(@user, post) do%>
            <div class="post_holder">
                <h3>Post: <%= post.id%></h3>

                <div>
                    <h3><%= post.title%></h3>
                    <p>Description: <%= post.text%></p>
                    <p>Number of comments: <%= post.comments_counter%></p>
                    <p>Number of likes: <%= post.likes_counter%></p>
                </div>
            </div>

         <% if can? :destroy, @post %>
          <%= form_with url: user_post_path(@user.id, post.id), method: :delete do |f| %>
            <%= f.submit 'Delete post', class: 'btn-danger btn-sm mx-2' %>
          <% end %>
        <% end %>
            <div>
              <% post.recent_comments.each do |comment| %>
                <p><%=comment.author.name %>: Comment <%= comment.id %> <%=comment.text %></p>
              <% end %>
          </div>
        <%end%>

    <div class="d-flex">
     <% if can? :destroy, @comment %>
       <%= form_with url: user_post_comment_path(post.author.id, post.id, comment.id), :method => :delete do |f| %>
         <%= f.submit 'Delete', class: 'glyphicon glyphicon-trash mx-2' %>
       <% end %>
     <% end %>
     </div>
<%end%>

     <button>Pagination</button>
</div>

app/views/posts/new.html.erb
<h1>Add a Post</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<p>post list</p>

<h1>Showing selected Post</h1>
<p>
 Title: <%= @post.title %>
</p>
<p>
 Text: <%= @post.text %>
</p>

<div class="post_show_container">
    <div class="show_header">
        <h1>Post <span><%=@post.id %></span> by <%= @user.name%></h1>
        <p>Comments: <%= @post.comments_counter || 0%></p>
        <p>likes: <%= @post.likes_counter || 0%></p>
    </div>

    <div class="post_details">
        <p>Post Text: <%= @post.text%></p>
    </div>

    <div class="action_div">
     <%= render 'posts/delete' %>
</div>

    <%= render "likes/like"%>

    <div class="comment_holder">
    <% @post.recent_comments.each do |comments| %>
        <p>Comment: <%= comments.text || "No comments added"%></p>
        <%end%>
    </div>

    <%= render "comments/form"%>

    <div class="comment_holder">
    <h5>All comments</h5>
    <% @post.all_comments.each do |comments| %>
        <p>Comment: <%= comments.text || "No comments added"%></p>
        <%end%>
    </div>


</div>

app/views/users/index.html.erb
<div class="nav">
    <%if user_admin_signed_in? %>
      <%= button_to "Sign Out", destroy_admin_session_path, method: :delete %>

     <button> <%= link_to "Edit your profile", edit_user_admin_registration_path %></button>

    <% else %>
      <%= link_to "Sign In",  new_user_admin_session_path %>
    <% end %>
</div>

<div>
     <%@users.each do |person|%>
        <%= link_to user_path(person.id) do%>
     <div class="user_image">
        <img src="<%= person.photo %>" />
     </div>  

     <div class="name_container">
         <h1><%= person.name %></h1> 
         <span>Number of posts: <%= person.posts_counter%></span>
     </div>
         <%end%>
     <%end%> 
</div>

app/views/users/show.html.erb
<p>show users</p>

<div class="container_user_show">
        <div class="photo_username">
            <div class="image_container">
                <img src= "<%= @user.photo %>" />
            </div>

            <div class="user_name">
                <h1>Name: <%= @user.name%></h1>
                <span>Number of posts: <%= @user.posts_counter || 0 %></span>
            </div>
        </div>

        <div class="bio_posts">

        <div class="bio">
            <h2>Bio</h2>
            <p><%= @user.bio%></p>
        </div>

    <%@user.most_recent_post.each do |posters|%>
    
        <div class="post">
            <h2>Post: <%= posters.id%></h2>
            <p>Posts Text:<%= posters.title || "comments unavailable"%></p>
            <p>Posts Text:<%= posters.text || "comments unavailable"%></p>
            <p>
                <span>Comments: <%= posters.comments_counter || 0%></span>
                <span>Likes: <%= posters.likes_counter || 0 %></span>
            </p>
        </div>
        
    <%end%>
  
    <%= link_to user_posts_path(@user) do %>
        <div class="all_post">
            <button>See all post</button>
        </div>
    <%end%>

</div>